name: DOJO Player

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version

      - name: Setup ShakaPackager
        run: |
          curl -LOJ https://github.com/shaka-project/shaka-packager/releases/download/v3.2.0/packager-linux-x64
          chmod +x packager-linux-x64
          sudo mv packager-linux-x64 /usr/local/bin/packager
          packager --version

      - name: Generate m3u8 from media/intro.mp4
        run: |
          chmod 755 media/intro.mp4
          if [ -f media/master.m3u8 ]; then
            echo "m3u8 files already exists"
          else
            echo "m3u8 files not found"
            packager \
              in=media/intro.mp4,stream=video,output=media/intro.mp4 \
              in=media/intro.mp4,stream=audio,output=media/intro.mp4 \
              --hls_master_playlist_output=media/master.m3u8 \
              --hls_playlist_type=VOD \
              --hls_base_url=https://thiagotn.github.io/dojo-player/media/
          fi

      - name: Add, commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Thiago Nogueira
          author_email: thiagotn@gmail.com
          message: "Add m3u8 files"
          add: "*"
