name: DOJO Player

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Setup ShakaPackager
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install shaka-packager
          shaka-packager --version
